import Vue from 'vue';
import Vuex from 'vuex';

Vue.use(Vuex);

export default new Vuex.Store({
  state: {
    name: '',
    level: 0,
    elements: [
      {
        name: 'angular',
        clicked: false,
        guessed: false,
        image: 'angular.png',
      },
      {
        name: 'angular',
        clicked: false,
        guessed: false,
        image: 'angular.png',
      },
      {
        name: 'vue',
        clicked: false,
        guessed: false,
        image: 'vue.png',
      },
      {
        name: 'vue',
        clicked: false,
        guessed: false,
        image: 'vue.png',
      },
      {
        name: 'react',
        clicked: false,
        guessed: false,
        image: 'react.png',
      },
      {
        name: 'react',
        clicked: false,
        guessed: false,
        image: 'react.png',
      },
      {
        name: 'ember',
        clicked: false,
        guessed: false,
        image: 'ember.png',
      },
      {
        name: 'ember',
        clicked: false,
        guessed: false,
        image: 'ember.png',
      },
      {
        name: 'css',
        clicked: false,
        guessed: false,
        image: 'css3.svg',
      },
      {
        name: 'css',
        clicked: false,
        guessed: false,
        image: 'css3.svg',
      },
      {
        name: 'javascript',
        clicked: false,
        guessed: false,
        image: 'javascript.png',
      },
      {
        name: 'javascript',
        clicked: false,
        guessed: false,
        image: 'javascript.png',
      },
      {
        name: 'svelte',
        clicked: false,
        guessed: false,
        image: 'svelte.png',
      },
      {
        name: 'svelte',
        clicked: false,
        guessed: false,
        image: 'svelte.png',
      },
      {
        name: 'html',
        clicked: false,
        guessed: false,
        image: 'html.png',
      },
      {
        name: 'html',
        clicked: false,
        guessed: false,
        image: 'html.png',
      },
      {
        name: 'java',
        clicked: false,
        guessed: false,
        image: 'java.png',
      },
      {
        name: 'java',
        clicked: false,
        guessed: false,
        image: 'java.png',
      },
      {
        name: 'php',
        clicked: false,
        guessed: false,
        image: 'php.png',
      },
      {
        name: 'php',
        clicked: false,
        guessed: false,
        image: 'php.png',
      },
      {
        name: 'csharp',
        clicked: false,
        guessed: false,
        image: 'csharp.png',
      },
      {
        name: 'csharp',
        clicked: false,
        guessed: false,
        image: 'csharp.png',
      },
      {
        name: 'scala',
        clicked: false,
        guessed: false,
        image: 'scala.png',
      },
      {
        name: 'scala',
        clicked: false,
        guessed: false,
        image: 'scala.png',
      },
      {
        name: 'python',
        clicked: false,
        guessed: false,
        image: 'python.png',
      },
      {
        name: 'python',
        clicked: false,
        guessed: false,
        image: 'python.png',
      },
      {
        name: 'go',
        clicked: false,
        guessed: false,
        image: 'go.png',
      },
      {
        name: 'go',
        clicked: false,
        guessed: false,
        image: 'go.png',
      },
      {
        name: 'elm',
        clicked: false,
        guessed: false,
        image: 'elm.png',
      },
      {
        name: 'elm',
        clicked: false,
        guessed: false,
        image: 'elm.png',
      },
      {
        name: 'laravel',
        clicked: false,
        guessed: false,
        image: 'laravel.png',
      },
      {
        name: 'laravel',
        clicked: false,
        guessed: false,
        image: 'laravel.png',
      },
      {
        name: 'symfony',
        clicked: false,
        guessed: false,
        image: 'symfony.png',
      },
      {
        name: 'symfony',
        clicked: false,
        guessed: false,
        image: 'symfony.png',
      },
      {
        name: 'django',
        clicked: false,
        guessed: false,
        image: 'django.png',
      },
      {
        name: 'django',
        clicked: false,
        guessed: false,
        image: 'django.png',
      },
      {
        name: 'codeigniter',
        clicked: false,
        guessed: false,
        image: 'codeigniter.png',
      },
      {
        name: 'codeigniter',
        clicked: false,
        guessed: false,
        image: 'codeigniter.png',
      },
      {
        name: 'node',
        clicked: false,
        guessed: false,
        image: 'node.png',
      },
      {
        name: 'node',
        clicked: false,
        guessed: false,
        image: 'node.png',
      },
      {
        name: 'graph',
        clicked: false,
        guessed: false,
        image: 'graph.png',
      },
      {
        name: 'graph',
        clicked: false,
        guessed: false,
        image: 'graph.png',
      },
      {
        name: 'mysql',
        clicked: false,
        guessed: false,
        image: 'mysql.png',
      },
      {
        name: 'mysql',
        clicked: false,
        guessed: false,
        image: 'mysql.png',
      },
      {
        name: 'mongodb',
        clicked: false,
        guessed: false,
        image: 'mongodb.png',
      },
      {
        name: 'mongodb',
        clicked: false,
        guessed: false,
        image: 'mongodb.png',
      },
      {
        name: 'flask',
        clicked: false,
        guessed: false,
        image: 'flask.png',
      },
      {
        name: 'flask',
        clicked: false,
        guessed: false,
        image: 'flask.png',
      },
      {
        name: 'spring',
        clicked: false,
        guessed: false,
        image: 'spring.png',
      },
      {
        name: 'spring',
        clicked: false,
        guessed: false,
        image: 'spring.png',
      },
      {
        name: 'gatsby',
        clicked: false,
        guessed: false,
        image: 'gatsby.png',
      },
      {
        name: 'gatsby',
        clicked: false,
        guessed: false,
        image: 'gatsby.png',
      },
      {
        name: 'haskell',
        clicked: false,
        guessed: false,
        image: 'haskell.png',
      },
      {
        name: 'haskell',
        clicked: false,
        guessed: false,
        image: 'haskell.png',
      },
      {
        name: 'docker',
        clicked: false,
        guessed: false,
        image: 'docker.png',
      },
      {
        name: 'docker',
        clicked: false,
        guessed: false,
        image: 'docker.png',
      },
      {
        name: 'npm',
        clicked: false,
        guessed: false,
        image: 'npm.png',
      },
      {
        name: 'npm',
        clicked: false,
        guessed: false,
        image: 'npm.png',
      },
      {
        name: 'yarn',
        clicked: false,
        guessed: false,
        image: 'yarn.png',
      },
      {
        name: 'yarn',
        clicked: false,
        guessed: false,
        image: 'yarn.png',
      },
      {
        name: 'ruby',
        clicked: false,
        guessed: false,
        image: 'ruby.png',
      },
      {
        name: 'ruby',
        clicked: false,
        guessed: false,
        image: 'ruby.png',
      },
      {
        name: 'vscode',
        clicked: false,
        guessed: false,
        image: 'vscode.png',
      },
      {
        name: 'vscode',
        clicked: false,
        guessed: false,
        image: 'vscode.png',
      },
    ],
  },
  getters: {
    getName: state => state.name,
    getElements: state => state.elements,
    getLevel: state => state.level,
  },
  mutations: {
    SET_NAME: (state, name) => { state.name = name; },
    SET_LEVEL: (state, level) => { state.level = level; },
  },
  actions: {
    setName({ commit }, name) {
      commit('SET_NAME', name);
    },
    setLevel({ commit }, level) {
      commit('SET_LEVEL', level);
    },
  },
});
